# Generated by Django 3.1.4 on 2020-12-18 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20201218_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_to_entry', to='expenses.entry', verbose_name='balance'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EU', 'EU'), ('RUB', 'RUB'), ('BYN', 'BYN')], default='rub', max_length=100, verbose_name='Currency'),
        ),
    ]
